### ISSUE TITLE
Add Bus Stop

### ISSUE THREAD

**Issue by StaRan17** [CankayaUniversity/ceng-407-408-2021-2022-Automated-Self-Learning-Bus-Simulation#2]
Implement Bus stops on scene and to agent file.

**Comment by metehankoc** [comment]
This isssue is closed after this [commit.](https://github.com/CankayaUniversity/ceng-407-408-2021-2022-Automated-Self-Learning-Bus-Simulation/commit/fa082d21bb4db27e5eb5c2c80c2fa575e18996ed)
