### ISSUE TITLE
Add new features to intersection roads

### ISSUE THREAD

**Issue by metehankoc** [CankayaUniversity/ceng-407-408-2021-2022-Automated-Self-Learning-Bus-Simulation#5]

**Comment by StaRan17** [comment]
Issue closed after [this](https://github.com/CankayaUniversity/ceng-407-408-2021-2022-Automated-Self-Learning-Bus-Simulation/commit/dfdba4dc1cf97419e916af045b3c0ddf9fc79c50) commit.
